### PR TITLE
Adding in the modularized functions into the analysis file

### LINKED ISSUE #23: Incorporating our functions into the report
We need to edit our report so that we're using our newly coded functions

### PR DESCRIPTION
**Pull request by WaleedMahmood1**

### CODE REVIEW

**Comment by meretelutz** [comment]
The plot_numeric_distributions function had a similar issue to Jake's in that it assumed the list of numeric features had elements that were numeric data type when really they're just strings

**Comment by WaleedMahmood1** [comment]
Oh you are completely right! I missed it, thanks for fixing it! I should have made it so to check that those specific columns in the data are of numeric type.

**Comment by meretelutz** [comment]
Everything is working on my machine! I haven't deleted any of the stuff you commented out yet. I'll do that and re-run just to double check.

**Comment by meretelutz** [comment]
Ready to merge, I think!

**Pull request merged**
