### PR TITLE
EDA file added

### PR DESCRIPTION
**Pull request by WaleedMahmood1**

### CODE REVIEW

**Comment by WaleedMahmood1** [comment]
@meretelutz I have a question regarding the visualizations. I was wondering, would it be a better idea to create the visualizations on the non-scaled features rather than the scaled versions of the features? 
Or maybe I might have missed something and we should be creating the visualizations on the scaled features😅

**Comment by meretelutz** [comment]
@WaleedMahmood1 I had the same question myself! Our original visualizations used the raw data. But then I was looking at the project Tiff gave us as an example and saw that she was using the scaled data for visualizations. So I thought I would do the same. I'm not entirely sure why we would chose one over the other, but once the data is scaled there's quite a bit of overlap, so maybe I'll go back and play around with it again.

**Comment by srfrew** [comment]
To chime in here I would vote for unscaled data so we have a sense of what everything is without modification, but don't have much rationale besides that.

**Comment by meretelutz** [comment]
I agree, I think that makes more sense. I changed it above.

**Pull request merged**
